# M52 regression test for the complexity gate's responsibility-TU guardrail.

param(
    [string]$Repo = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'
$failures = 0

function Check($condition, [string]$message) {
    if ($condition) { Write-Host "PASS: $message" }
    else { Write-Host "FAIL: $message"; $script:failures++ }
}

function Write-Utf8NoBom([string]$Path, [string]$Value) {
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Value, $encoding)
}

function Invoke-Complexity([string]$Root) {
    $out = Join-Path $env:TEMP ("m52_complexity_" + [guid]::NewGuid().ToString('N') + '.json')
    try {
        & (Join-Path $Repo 'scripts/complexity_gate.ps1') -Repo $Root -Json -OutJson $out | Out-Null
        return (Get-Content -Raw -Encoding UTF8 $out | ConvertFrom-Json)
    }
    finally {
        Remove-Item -LiteralPath $out -ErrorAction SilentlyContinue
    }
}

function New-Source([string]$Path, [int]$Lines) {
    $content = [System.Collections.Generic.List[string]]::new()
    [void]$content.Add('// generated by the M52 gate regression')
    for ($i = 1; $i -lt $Lines; ++$i) {
        [void]$content.Add('// filler')
    }
    Write-Utf8NoBom $Path ($content -join "`n")
}

# A function whose signature spans several lines (Allman parameter list). The
# gate used to type the brace from the previous line only, so this frame was
# treated as a block and its span/CC were never measured.
function New-MultilineFunctionSource([string]$Path, [string[]]$Signature, [int]$BodyLines) {
    $content = [System.Collections.Generic.List[string]]::new()
    [void]$content.Add('// generated by the M52 gate regression')
    foreach ($line in $Signature) { [void]$content.Add($line) }
    [void]$content.Add('{')
    for ($i = 0; $i -lt $BodyLines; ++$i) { [void]$content.Add('    // filler') }
    [void]$content.Add('}')
    Write-Utf8NoBom $Path ($content -join "`n")
}

$tmp = Join-Path $Repo (".m52_complexity_tmp_" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path (Join-Path $tmp 'src') -Force | Out-Null
try {
    New-Source (Join-Path $tmp 'src/mainwindow_oversized.cpp') 1001
    $oversized = Invoke-Complexity $tmp
    $finding = @($oversized.files | Where-Object { $_.file -match 'mainwindow_oversized' }) | Select-Object -First 1
    Check ($null -ne $finding -and $finding.level -eq 'fail' -and $finding.cap -eq 1000) `
        'an oversized responsibility TU is a hard finding at the 1000-line ceiling'

    New-Source (Join-Path $tmp 'src/mainwindow_part_a.cpp') 900
    New-Source (Join-Path $tmp 'src/mainwindow_part_b.cpp') 900
    Remove-Item -LiteralPath (Join-Path $tmp 'src/mainwindow_oversized.cpp')
    $split = Invoke-Complexity $tmp
    Check ($split.hardFails -eq 0) 'legal responsibility TUs below the ceiling pass hard checks'
    Check (@($split.files | Where-Object { $_.level -eq 'fail' }).Count -eq 0) `
        'legal responsibility split has no file-level hard finding'
    Check (@($split.files | Where-Object { $_.file -match 'mainwindow_part_' -and $_.level -eq 'warn' }).Count -eq 2) `
        'legal responsibility split remains visible as advisory size feedback'

    $real = Invoke-Complexity $Repo
    Check ($real.hardFails -eq 0) "real tree has zero complexity hard failures (got $($real.hardFails))"

    # ---- frame typing: a multi-line signature must still be measured ---------
    # Regression for the hole where `$prefix` was built from the previous line
    # only, so an Allman parameter list typed the body as a block and skipped the
    # function caps entirely.
    Remove-Item -LiteralPath (Join-Path $tmp 'src/mainwindow_part_a.cpp')
    Remove-Item -LiteralPath (Join-Path $tmp 'src/mainwindow_part_b.cpp')
    New-MultilineFunctionSource (Join-Path $tmp 'src/multiline_sig.cpp') @(
        'void oversized(std::unique_ptr<int> first,',
        '               const std::string &second,',
        '               int third)') 140
    $multiline = Invoke-Complexity $tmp
    $finding = @($multiline.functions | Where-Object { $_.span -gt 120 }) | Select-Object -First 1
    Check ($null -ne $finding -and $finding.span -ge 141) `
        'a multi-line (Allman) signature is measured, not skipped as a block'
    Check ($multiline.hardFails -ge 1) 'the over-cap multi-line function is a hard finding'

    # A parameter line that carries its own balanced parens (std::function<...>)
    # must not stop the signature walk early.
    Remove-Item -LiteralPath (Join-Path $tmp 'src/multiline_sig.cpp')
    New-MultilineFunctionSource (Join-Path $tmp 'src/balanced_param.cpp') @(
        'void oversized(std::function<void(const Result &)> callback,',
        '               const std::string &name)') 140
    $balanced = Invoke-Complexity $tmp
    Check (@($balanced.functions | Where-Object { $_.span -gt 120 }).Count -eq 1) `
        'a balanced-paren parameter line does not truncate the signature walk'

    # ... and a namespace block must not be mistaken for a function.
    Remove-Item -LiteralPath (Join-Path $tmp 'src/balanced_param.cpp')
    New-MultilineFunctionSource (Join-Path $tmp 'src/namespace_block.cpp') @(
        'namespace fake {') 200
    $namespace = Invoke-Complexity $tmp
    Check ($namespace.hardFails -eq 0) 'a namespace body is not reported as an over-cap function'
}
finally {
    Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "complexity_gate_test: $failures failure(s)"
exit $failures
