# M52 regression test for the complexity gate's responsibility-TU guardrail.

param(
    [string]$Repo = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'
$failures = 0

function Check($condition, [string]$message) {
    if ($condition) { Write-Host "PASS: $message" }
    else { Write-Host "FAIL: $message"; $script:failures++ }
}

function Write-Utf8NoBom([string]$Path, [string]$Value) {
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Value, $encoding)
}

function Invoke-Complexity([string]$Root) {
    $out = Join-Path $env:TEMP ("m52_complexity_" + [guid]::NewGuid().ToString('N') + '.json')
    try {
        & (Join-Path $Repo 'scripts/complexity_gate.ps1') -Repo $Root -Json -OutJson $out | Out-Null
        return (Get-Content -Raw -Encoding UTF8 $out | ConvertFrom-Json)
    }
    finally {
        Remove-Item -LiteralPath $out -ErrorAction SilentlyContinue
    }
}

function New-Source([string]$Path, [int]$Lines) {
    $content = [System.Collections.Generic.List[string]]::new()
    [void]$content.Add('// generated by the M52 gate regression')
    for ($i = 1; $i -lt $Lines; ++$i) {
        [void]$content.Add('// filler')
    }
    Write-Utf8NoBom $Path ($content -join "`n")
}

$tmp = Join-Path $Repo (".m52_complexity_tmp_" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path (Join-Path $tmp 'src') -Force | Out-Null
try {
    New-Source (Join-Path $tmp 'src/mainwindow_oversized.cpp') 1001
    $oversized = Invoke-Complexity $tmp
    $finding = @($oversized.files | Where-Object { $_.file -match 'mainwindow_oversized' }) | Select-Object -First 1
    Check ($null -ne $finding -and $finding.level -eq 'fail' -and $finding.cap -eq 1000) `
        'an oversized responsibility TU is a hard finding at the 1000-line ceiling'

    New-Source (Join-Path $tmp 'src/mainwindow_part_a.cpp') 900
    New-Source (Join-Path $tmp 'src/mainwindow_part_b.cpp') 900
    Remove-Item -LiteralPath (Join-Path $tmp 'src/mainwindow_oversized.cpp')
    $split = Invoke-Complexity $tmp
    Check ($split.hardFails -eq 0) 'legal responsibility TUs below the ceiling pass hard checks'
    Check (@($split.files | Where-Object { $_.level -eq 'fail' }).Count -eq 0) `
        'legal responsibility split has no file-level hard finding'
    Check (@($split.files | Where-Object { $_.file -match 'mainwindow_part_' -and $_.level -eq 'warn' }).Count -eq 2) `
        'legal responsibility split remains visible as advisory size feedback'

    $real = Invoke-Complexity $Repo
    Check ($real.hardFails -eq 0) "real tree has zero complexity hard failures (got $($real.hardFails))"
}
finally {
    Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "complexity_gate_test: $failures failure(s)"
exit $failures
