# M23 Build-Health — Test Matrix (auto-generated).
#
# The reviewer asked to stop hand-maintaining docs and instead auto-generate the
# test matrix. This script scans every test source (tests/, src/*test*,
# src/benchmark) and produces docs/test_matrix.md: a Feature x TestType matrix
# (Unit / Integration / Benchmark / UI / Vision) derived from real code, so it
# is always accurate and never rots.
#
# Re-run in CI (publish-health) so the matrix reflects the latest tree.

[CmdletBinding()]
param(
    [string]$Repo = (Resolve-Path (Join-Path $PSScriptRoot '..')),
    [string]$Out = (Join-Path $Repo 'docs/test_matrix.md')
)

$ErrorActionPreference = 'Stop'

# Feature -> keywords used to tag a test source by grepping its content.
$featureKeywords = [ordered]@{
    'Browse'         = @('browse', 'directorytree', 'thumbnailpanel', 'navigat', 'zoom', 'folder')
    'Compare'        = @('compare', 'splitscreen', 'splitview', 'overlay', 'blink', 'diff', 'roi', 'sync')
    'Thumbnail'      = @('thumbnail')
    'Metadata'       = @('metadata', 'exif', 'rawmetadata', 'analyzer')
    'Export'         = @('export', 'report', 'exporter')
    'Batch'          = @('batch', 'bulk')
    'Workspace'      = @('workspace')
    'RAW'            = @('rawdecoder', 'raw', 'decoderregistry')
    'Cache'          = @('cachemanager', 'cache')
    'Pipeline'       = @('pipeline', 'scheduler')
    'Pixel Inspector' = @('pixel', 'inspector')
    'Diff Engine'    = @('diffengine', 'diff')
    'Plugin'         = @('plugin')
}

$columns = @('Unit', 'Integration', 'Benchmark', 'UI', 'Vision')

# Collect test sources.
$sources = [System.Collections.Generic.List[object]]::new()
$sources.AddRange(@(Get-ChildItem -Path (Join-Path $Repo 'tests') -Recurse -Include *.cpp -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch 'testdata' }))
$sources.AddRange(@(Get-ChildItem -Path (Join-Path $Repo 'src') -Recurse -Include *.cpp -ErrorAction SilentlyContinue | Where-Object { $_.Name -match 'test' -or $_.Name -match '_test' }))
$sources.AddRange(@(Get-ChildItem -Path (Join-Path $Repo 'src/benchmark') -Recurse -Include *.cpp -ErrorAction SilentlyContinue))

# matrix[feature] = { Unit=@(), Integration=@(), Benchmark=@(), UI=@(), Vision=@() }
$matrix = @{}
foreach ($k in $featureKeywords.Keys) { $matrix[$k] = @{}; foreach ($c in $columns) { $matrix[$k][$c] = [System.Collections.Generic.List[string]]::new() } }

function Type-Of($rel) {
    if ($rel -match 'tests[\\/]plugin') { return 'Integration' }
    if ($rel -match 'tests[\\/]ui_fixture') { return 'UI' }
    if ($rel -match 'tests[\\/]vision') { return 'Vision' }
    if ($rel -match 'test_workflow') { return 'UI' }
    if ($rel -match 'benchmark') { return 'Benchmark' }
    return 'Unit'
}

foreach ($f in $sources) {
    $rel = $f.FullName.Substring($Repo.Length).TrimStart('\', '/')
    try { $content = (Get-Content $f.FullName -Raw -Encoding UTF8).ToLower() } catch { $content = '' }
    $type = Type-Of $rel
    $tagged = $false
    foreach ($feat in $featureKeywords.Keys) {
        foreach ($kw in $featureKeywords[$feat]) {
            if ($content.Contains($kw)) {
                if (-not $matrix[$feat][$type].Contains($rel)) { $matrix[$feat][$type].Add($rel) }
                $tagged = $true
                break
            }
        }
    }
    if (-not $tagged) {
        # Untagged test files still count as Unit coverage of (general).
        if (-not $matrix.ContainsKey('(general)')) {
            $matrix['(general)'] = @{}; foreach ($c in $columns) { $matrix['(general)'][$c] = [System.Collections.Generic.List[string]]::new() }
        }
        if (-not $matrix['(general)'][$type].Contains($rel)) { $matrix['(general)'][$type].Add($rel) }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# MViewer — Test Matrix')
[void]$sb.AppendLine()
[void]$sb.AppendLine('> Auto-generated by `scripts/test_matrix.ps1` from the current tree. Do NOT edit by hand — re-run the script (CI `publish-health` does this every night).')
[void]$sb.AppendLine()
$generated = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$commit = ((git -C $Repo rev-parse --short HEAD 2>$null) + '')
[void]$sb.AppendLine("Generated: **$generated** - commit $commit")
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Feature Coverage')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Feature | Unit | Integration | Benchmark | UI | Vision |')
[void]$sb.AppendLine('|---|---|---|---|---|---|')
foreach ($feat in $featureKeywords.Keys + @('(general)')) {
    if (-not $matrix.ContainsKey($feat)) { continue }
    $cells = foreach ($c in $columns) {
        $n = $matrix[$feat][$c].Count
        if ($n -eq 0) { '-' } else { "$n" }
    }
    [void]$sb.AppendLine("| $feat | $($cells -join ' | ') |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('Legend: a number = count of test sources covering that feature in that test type. `—` = no dedicated test source detected (gap to fill).')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Test Inventory')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Test source | Type | Feature tags |')
[void]$sb.AppendLine('|---|---|---|')
foreach ($f in $sources) {
    $rel = $f.FullName.Substring($Repo.Length).TrimStart('\', '/')
    $type = Type-Of $rel
    try { $content = (Get-Content $f.FullName -Raw -Encoding UTF8).ToLower() } catch { $content = '' }
    $tags = [System.Collections.Generic.List[string]]::new()
    foreach ($feat in $featureKeywords.Keys) {
        foreach ($kw in $featureKeywords[$feat]) {
            if ($content.Contains($kw)) { $tags.Add($feat); break }
        }
    }
    if ($tags.Count -eq 0) { $tags.Add('(general)') }
    [void]$sb.AppendLine("| ``$rel`` | $type | $($tags -join ', ') |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('---')
[void]$sb.AppendLine('_This matrix is regenerated automatically. The M23 policy: every shipped feature MUST have at least one regression test — add the test, then this matrix updates itself._')

Set-Content -Path $Out -Value $sb.ToString() -Encoding UTF8
Write-Host "test_matrix: wrote $($sources.Count) test sources -> $Out"
