#!/usr/bin/env python3
"""MViewer deterministic test-data generator (P0-01 reproducibility fix).

testdata/ is git-ignored by design: generated images must never be committed.
ONLY this script is tracked (see .gitignore: `testdata/*` + `!testdata/generate_fixtures.py`),
so a clean checkout / CI runner can rebuild the exact fixture corpus the
decode-dependent CTest suites require.

Usage:
  python testdata/generate_fixtures.py [--size N] [--check] [--ensure]
    default   generate (idempotent) the fixture corpus under testdata/
    --size N  golden tier dimension (default 256)
    --check   validate the required fixture set exists with correct dimensions
              (exit 1 on mismatch; does not write anything)
    --ensure  generate anything missing, then validate (used by the
              testdata_generator_gate CTest)

Exit codes: 0 = ok/skip, 1 = failure (missing Pillow with missing fixtures,
dimension mismatch, or write failure).
"""

import argparse
import os
import sys

# Required fixtures: relative path -> (width, height)
REQUIRED = {
    "golden/256x256/checker_256x256.jpg": (256, 256),
    "golden/256x256/flat_color_256x256.jpg": (256, 256),
    "golden/256x256/flat_color_256x256.png": (256, 256),
    "golden/256x256/flat_color_256x256.bmp": (256, 256),
    "golden/256x256/flat_color_256x256.tiff": (256, 256),
    "golden/256x256/gradient_256x256.png": (256, 256),
    # Large-image fixture used by core_tests / asset acceptance. A REAL 6000x4000
    # JPEG (the historical file in golden/256x256 was mislabeled 256x256).
    "golden/pixnio-6000x4000.jpg": (6000, 4000),
}

# Corrupted fixtures: the decoder must reject them gracefully (null ImageData),
# never crash. Generated by truncating valid encodings of a small image.
CORRUPTED = ("truncated.png", "truncated.jpg", "truncated.tiff")


def root_dir() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def check_fixtures(root: str) -> bool:
    """Validate every required fixture exists and decodes to the expected size."""
    from PIL import Image

    ok = True
    for rel, (w, h) in sorted(REQUIRED.items()):
        p = os.path.join(root, rel)
        if not os.path.isfile(p):
            print("MISSING %s" % rel)
            ok = False
            continue
        try:
            with Image.open(p) as im:
                if im.size != (w, h):
                    print("DIMS %s got %dx%d want %dx%d" % (rel, im.size[0], im.size[1], w, h))
                    ok = False
        except Exception as exc:  # noqa: BLE001 - any decode failure is a gate failure
            print("DECODE_FAIL %s: %s" % (rel, exc))
            ok = False
    return ok


def make_checker(size: int):
    from PIL import Image, ImageDraw

    im = Image.new("RGB", (size, size), "black")
    d = ImageDraw.Draw(im)
    cell = max(1, size // 8)
    for y in range(0, size, cell):
        for x in range(0, size, cell):
            if ((x // cell) + (y // cell)) % 2 == 0:
                d.rectangle([x, y, x + cell - 1, y + cell - 1], fill=(255, 255, 255))
    return im


def make_flat(size: int, rgb=(80, 160, 220)):
    from PIL import Image

    return Image.new("RGB", (size, size), rgb)


def make_gradient(size: int):
    from PIL import Image

    g = Image.linear_gradient("L").resize((size, size))
    return Image.merge("RGB", (g, g.transpose(Image.Transpose.ROTATE_90), g))


def make_photo(w: int, h: int):
    """Real 6000x4000 photo-like fixture: 2D gradient + deterministic noise (fast C path)."""
    from PIL import Image, ImageFilter

    gv = Image.linear_gradient("L").resize((w, h))                       # vertical gradient
    gh = Image.linear_gradient("L").resize((h, w)).rotate(90).resize((w, h))  # horizontal gradient
    noise = Image.effect_noise((w, h), 24).convert("L")
    base = Image.blend(gv, gh, 0.5)
    im = Image.blend(base, noise, 0.35)
    rgb = Image.merge("RGB", (im, im.rotate(180), im.transpose(Image.Transpose.FLIP_LEFT_RIGHT)))
    return rgb.filter(ImageFilter.GaussianBlur(0.5))
def generate(root: str, size: int) -> bool:
    from PIL import Image

    tier = os.path.join(root, "golden", "%dx%d" % (size, size))
    os.makedirs(tier, exist_ok=True)
    os.makedirs(os.path.join(root, "golden"), exist_ok=True)

    def save(im, rel, fmt=None):
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        if fmt is None:
            fmt = os.path.splitext(p)[1].lstrip(".").upper()
        if fmt == "JPG":
            fmt = "JPEG"
        kwargs = {"quality": 90} if fmt == "JPEG" else {}
        im.save(p, fmt, **kwargs)
        print("WROTE %s" % rel)
    save(make_checker(size), "golden/%dx%d/checker_%dx%d.jpg" % (size, size, size, size))
    save(make_flat(size), "golden/%dx%d/flat_color_%dx%d.jpg" % (size, size, size, size))
    save(make_flat(size), "golden/%dx%d/flat_color_%dx%d.png" % (size, size, size, size))
    save(make_flat(size), "golden/%dx%d/flat_color_%dx%d.bmp" % (size, size, size, size))
    save(make_flat(size), "golden/%dx%d/flat_color_%dx%d.tiff" % (size, size, size, size))
    save(make_gradient(size), "golden/%dx%d/gradient_%dx%d.png" % (size, size, size, size))
    save(make_photo(6000, 4000), "golden/pixnio-6000x4000.jpg")

    # Corrupted fixtures: truncate valid encodings of a small checker so the
    # decoder has real-but-broken streams to reject gracefully.
    tmp = make_checker(64)
    corrupt_dir = os.path.join(root, "corrupted")
    os.makedirs(corrupt_dir, exist_ok=True)
    for name, fmt in (("truncated.png", "PNG"), ("truncated.jpg", "JPEG"), ("truncated.tiff", "TIFF")):
        buf = bytearray()
        tmp.save(os.path.join(corrupt_dir, "_full." + name.rsplit(".", 1)[1]), fmt, quality=90)
        with open(os.path.join(corrupt_dir, "_full." + name.rsplit(".", 1)[1]), "rb") as f:
            buf = bytearray(f.read(96))
        os.remove(os.path.join(corrupt_dir, "_full." + name.rsplit(".", 1)[1]))
        with open(os.path.join(corrupt_dir, name), "wb") as f:
            f.write(bytes(buf))
        print("WROTE corrupted/%s" % name)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description="MViewer test-data generator")
    ap.add_argument("--size", type=int, default=256)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--ensure", action="store_true")
    args = ap.parse_args()

    root = root_dir()
    if args.size < 16:
        print("invalid --size %d" % args.size)
        return 1

    try:
        import PIL  # noqa: F401
    except ImportError:
        # Pillow is the only generator dependency. If every required fixture
        # already exists we can still pass (validation needs Pillow too, so
        # fall back to existence check); if something is missing we must fail
        # loudly instead of silently shipping an incomplete corpus.
        missing = [rel for rel in REQUIRED if not os.path.isfile(os.path.join(root, rel))]
        if missing:
            print("Pillow required to generate missing fixtures: %s" % ", ".join(missing))
            return 1
        print("SKIP Pillow unavailable; existing fixtures present")
        return 0

    if args.ensure:
        missing = [rel for rel in REQUIRED if not os.path.isfile(os.path.join(root, rel))]
        if missing:
            generate(root, args.size)
    elif not args.check:
        generate(root, args.size)

    ok = check_fixtures(root)
    print("FIXTURE_CHECK %s" % ("OK" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
