"""Generate testdata fixture catalog from existing golden images."""
from pathlib import Path

GOLDEN = Path("testdata/golden")
OUT = Path("testdata/CATALOG.md")

lines = ["# Golden Image Catalog",
         "Auto-generated by `testdata/generate_fixtures.py`. Do not edit.",
         "",
         "| Directory | File | Format | Size |",
         "|-----------|------|--------|------|"]

for subdir in sorted(GOLDEN.iterdir()):
    if not subdir.is_dir() or subdir.name == ".gitkeep":
        continue
    for f in sorted(subdir.iterdir()):
        if f.suffix.lower() in {'.png', '.jpg', '.bmp', '.tiff', '.jpeg'}:
            lines.append(f"| {subdir.name}/ | {f.name} | {f.suffix[1:].upper()} | {f.stat().st_size:,} bytes |")

OUT.write_text('\n'.join(lines) + '\n')
print(f"Wrote {OUT} with {len(lines) - 4} entries.")
